### ISSUE TITLE
ChineseFoodNet百度云资源失效

### ISSUE THREAD

**Issue by Nyxeye** [powerli2002/ChineseFoodNet-Resnet50#1]
大佬好，我在做神经网络，然后想用下ChineseFoodNet这个dataset, 可是发现官网那个链接点进去出错了，然后您README的图片dataset那个百度云也失效了。想问下能不能更新下或者什么其他方式分享一下吗

**Comment by powerli2002** [comment]
用这个吧  https://pan.baidu.com/s/19lPkSGhMwe5QLLXHNOu-Zw?pwd=7rur
