### ISSUE TITLE
准确率

### ISSUE THREAD

**Issue by newplayer058** [powerli2002/ChineseFoodNet-Resnet50#3]
两个准确率文件，是原网络和新网络的准确率嘛

**Comment by powerli2002** [comment]
都是resnet50的。top1就是输出是否为真，top5是前五个结果是否包含真值。

**Comment by newplayer058** [comment]
感谢

**Comment by newplayer058** [comment]
两个网络的区别，主要在model文件夹里加入的resnet50文件吗

**Comment by powerli2002** [comment]
> 两个网络的区别，主要在model文件夹里加入的resnet50文件吗

对，最后用的这个。那个wide resnet是尝试，不用看。

**Comment by newplayer058** [comment]
> > 两个网络的区别，主要在model文件夹里加入的resnet50文件吗
> 
> 对，最后用的这个。那个wide resnet是尝试，不用看。

那我如果只把这个py文件考进原网络就行了吗

**Comment by powerli2002** [comment]
> > > 两个网络的区别，主要在model文件夹里加入的resnet50文件吗
> > 
> > 
> > 对，最后用的这个。那个wide resnet是尝试，不用看。
> 
> 那我如果只把这个py文件考进原网络就行了吗

你可以自己试试，对比着看看

**Comment by newplayer058** [comment]
好的，这个checkpoint函数，是自定义的吗
![1723088927080](https://github.com/user-attachments/assets/a3732432-32d0-4341-bea1-d9cf33deb880)

**Comment by powerli2002** [comment]
checkpoint是个字典，存储当前运行信息，包括权重。可以自定义

**Comment by newplayer058** [comment]
![1723514107974](https://github.com/user-attachments/assets/31b4c1ec-4091-407b-a786-550d66c30fba)
楼主，这些model_data中的文件可以分享一下吗

**Comment by powerli2002** [comment]
看readme，有权重分享，没过期。

**Comment by newplayer058** [comment]
> 看readme，有权重分享，没过期。

这些不同的都可以用那一个是嘛

**Comment by powerli2002** [comment]
> > 看readme，有权重分享，没过期。
> 
> 这些不同的都可以用那一个是嘛

只有resnet50网络的权重

**Comment by newplayer058** [comment]
![1723609561887](https://github.com/user-attachments/assets/8e552c23-e779-4b6d-b14c-aec9d36b1f68)
lou'zh楼主有遇到过这种问题吗

**Comment by powerli2002** [comment]
并没有，看起来是group里没有这个key，你可以调试看看group这个是从哪来的？看你有没有加上这个maximize。这是我的代码加上我的模型吗

**Comment by newplayer058** [comment]
> 并没有，看起来是group里没有这个key，你可以调试看看group这个是从哪来的？看你有没有加上这个maximize。这是我的代码加上我的模型吗

使用的您这里的代码，下载之后运行会有，那个checkpoint没定义，然后下载了，百度云里的权重导进去之后直接运行，会报
![Q3JG} Z%%JQ0U2$O6)$3RUH](https://github.com/user-attachments/assets/8318d93d-ae62-4997-92ca-442922a7b800)
这个错误
然后我觉得应该是模型没有用resnet50的问题，之后我把这里的模型进行了切换
![Z 2K@8CY~QM@4G_D7E{8L@G](https://github.com/user-attachments/assets/9ea8dc0c-e374-44c8-bde6-02c36ff4dd21)
就出现了这个问题
![{4O7TLQ$M0J B5TKFSM6OB](https://github.com/user-attachments/assets/1d4169ab-e7d7-48ce-99e2-d2544a759893)
很绝望T.T

**Comment by newplayer058** [comment]
> 并没有，看起来是group里没有这个key，你可以调试看看group这个是从哪来的？看你有没有加上这个maximize。这是我的代码加上我的模型吗
使用的您这里的代码，下载之后运行会有，那个checkpoint没定义，然后下载了，百度云里的权重导进去之后直接运行，会报
![image](https://github.com/user-attachments/assets/10b2a8ef-a167-440e-badd-8887a19587b1)
这个错误
然后我觉得应该是模型没有用resnet50的问题，之后我把这里的模型进行了切换
![image](https://github.com/user-attachments/assets/2cf7f82a-22d7-4269-9bb3-712eb1254dbf)
就出现了这个问题
![image](https://github.com/user-attachments/assets/94d70e74-70dd-4316-8373-2046053a1700)
很绝望T.T

**Comment by newplayer058** [comment]
楼主有看到吗

**Comment by powerli2002** [comment]
你可以先试一下我提交的这版本，注释的代码稍微修改了一下。我自己试的可以读取模型。

**Comment by newplayer058** [comment]
> 你可以先试一下我提交的这版本，注释的代码稍微修改了一下。我自己试的可以读取模型。

太感谢了，我试一试

**Comment by newplayer058** [comment]
> 你可以先试一下我提交的这版本，注释的代码稍微修改了一下。我自己试的可以读取模型

好像是能搭载模型，就是跑不完第一轮测试

**Comment by newplayer058** [comment]
> 你可以先试一下我提交的这版本，注释的代码稍微修改了一下。我自己试的可以读取模型。

楼主能跑完一轮学习嘛

**Comment by newplayer058** [comment]
模型能搭载，但是数据跑不完一轮


> 你可以先试一下我提交的这版本，注释的代码稍微修改了一下。我自己试的可以读取模型。

**Comment by newplayer058** [comment]
楼主有不加载权重的代码

**Comment by powerli2002** [comment]
我是可以进行正常训练的，能跑多轮。
![image](https://github.com/user-attachments/assets/e58e9a00-8cb9-4de4-a6c6-e12d6091d2b1)

**Comment by newplayer058** [comment]
> 我是可以进行正常训练的，能跑多轮。 ![image](https://private-user-images.githubusercontent.com/97718726/365491668-e58e9a00-8cb9-4de4-a6c6-e12d6091d2b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDkxNzksIm5iZiI6MTcyNTg0ODg3OSwicGF0aCI6Ii85NzcxODcyNi8zNjU0OTE2NjgtZTU4ZTlhMDAtOGNiOS00ZGU0LWE2YzYtZTEyZDYwOTFkMmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyMjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYTdlY2I5ZGMzNDc0ODk4NjgxMjY4ZGNlNDhhYTkyMDQ3NTVjNTk2Yjc5ZDkxZmNhOTZhYjIyYzIzNWIxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gSOByry5eDwkuTKl-EvSThF-1QBz8nlVi8IVDogz9y0)

那应该是pytorch的版本不兼容
