### ISSUE TITLE
requirements.txt里面的文件

### ISSUE THREAD

**Issue by zhixin-zheng** [powerli2002/ChineseFoodNet-Resnet50#4]
![QQ_1723216474389](https://github.com/user-attachments/assets/f6136c97-702f-4dfa-a198-32e21028fe03)
您好，请问requirements.txt里面的这些本地文件从哪里获取呢，是必要的吗

**Comment by powerli2002** [comment]
导出有问题，修改了一下，其实主要就是pytorch和pyqt，有的是包冗余的，如果不全装的话，可以看报错装一下就行。

**Comment by zhengzx04** [comment]
好的好的感谢回答

**Comment by newplayer058** [comment]
同学你有出现zh这种问题吗
![NPCN`IS2%(@BG_8V~5CYY2B](https://github.com/user-attachments/assets/538b7a55-7326-420c-ac7c-fe38a03bd026)
